defaults:
  - _self_

model: ???
dataset: "/Users/philipphager/Documents/GitHub/clax-datasets/data/wscd-2012/YandexClicks.txt"

train_sessions: ???
val_sessions: ???
test_sessions: ???

eval_train_queries_only: True
experiment: ""
