defaults:
  - _self_

model: ???
dataset: "/Users/philipphager/Documents/GitHub/clax-datasets/data/wscd-2012/YandexClicks.txt"

train_sessions: ???
val_sessions: ???
test_sessions: ???

min_train_sessions_per_eval_query: 0
experiment: ""
