# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    mem_gb: 128
    cpus_per_task: 16
    array_parallelism: 10
    partition: cpu
    timeout_min: 7_200
